app:
  jwt:
    secret-key: am9pbmVkZWxlY3RyaWNpdHltaWxrcGxlYXN1cmVhc3BsZWFzZXdpdGh3aWxkaW50ZXI=
    expiration-ms: '8640000'
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    password: abdullah1223
    username: abdullah
    url: jdbc:h2:mem:phonebookdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  security:
    user:
      password: abdullah1223
      name: abdullah
  h2:
    console:
      path: /h2-console
      enabled: 'true'
springdoc:
  api-docs:
    path: /api-docs
server:
  port: '8080'
