app:
  jwt:
    secret-key: am9pbmVkZWxlY3RyaWNpdHltaWxrcGxlYXN1cmVhc3BsZWFzZXdpdGh3aWxkaW50ZXI=
    expiration-ms: '8640000'
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1223

  security:
    user:
      password: abdullah1223
      name: abdullah

springdoc:
  api-docs:
    path: /api-docs
server:
  port: '8080'
